[project]
name = "chap-gis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "knutdrand", email = "knutdrand@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.33.1",
    "shapely>=2.0",
]

[project.scripts]
chap-gis = "chap_gis:main"

[build-system]
requires = ["uv_build>=0.9.30,<0.10.0"]
build-backend = "uv_build"
